### PR TITLE
Unifying Prefix Configuration to the config.ini file

### PR DESCRIPTION
**Pull request by LoboMetalurgico**

### CODE REVIEW

**Comment by Techguy9078** [comment]
I believe this is a good pull request further evaluation will be done.

**Comment by Yamgirly** [comment]
We're not continuing on with this version of the bot

**Comment by Yamgirly** [comment]
Can someone close this PR

**Comment by Techguy9078** [comment]
Yes, Sorry I forgot a rebuild of the bot is in progress

**Pull request closed without merging**
